# docker-compose.yml
version: '3.9'

services:
  web-api:
    container_name: web-api
    build:
      context: .
      target: final
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:16